### ISSUE TITLE
Comiling error with Portenta H7

### ISSUE THREAD

**Issue by wbadry** [khoih-prog/SAMD_TimerInterrupt#1]
Hello,
Although the [documentation](https://www.arduino.cc/reference/en/libraries/samd_timerinterrupt/) stated that it is compatible with Portneta H7, I received a compiling error.  

Is there anything I can make, or the STM32H747X is not supported?

Thanks

**Comment by khoih-prog** [comment]
This library is for **SAMD** boards, such as SAMD21/SAMD51, while Portenta H7 is **STM32H7 using MBED OS.**
Therefore, the Portenta H7 will never be supported by this library.

Even the [**STM32_TimerInterrupt library**](https://github.com/khoih-prog/STM32_TimerInterrupt) doesn't not support that Portenta H7 boards.

**Comment by khoih-prog** [comment]
I just have a look at the [samd_timerinterrupt documentation](https://www.arduino.cc/reference/en/libraries/samd_timerinterrupt/) you mentioned. It is written by someone else and certainly is mistaken and must be corrected.

**Comment by khoih-prog** [comment]
You can now use my new [**Portenta_H7_TimerInterrupt** Library](https://github.com/khoih-prog/Portenta_H7_TimerInterrupt)

---

### Initial Releases v1.2.1

1. Initial coding to support **Portenta_H7 boards** such as Portenta_H7 Rev2 ABX00042, etc., using [**ArduinoCore-mbed mbed_portenta** core](https://github.com/arduino/ArduinoCore-mbed)
2. Permit up to 16 super-long-time, super-accurate ISR-based timers to avoid being blocked
3. Using cpp code besides Impl.h code to use if Multiple-Definition linker error.
4. Bump version to v1.2.1 to sync with [STM32_TimerInterrupt library](https://github.com/khoih-prog/STM32_TimerInterrupt)
