### ISSUE TITLE
doesn't compile with Adafruit Feather M0

### ISSUE THREAD

**Issue by generationmake** [khoih-prog/SAMD_TimerInterrupt#2]
### Describe the bug

The example code doesn't compile with Adafruit Feather M0.

### Steps to Reproduce

chose Adafruit Feather M0 as board and compile

### Expected behavior

compile without error

### Additional context

It seems to be related to these lines in the code:
https://github.com/khoih-prog/SAMD_TimerInterrupt/blob/fbf8a91861b85312b21a257e89221e54fdceed2b/src/SAMDTimerInterrupt.h#L94-L97

It somehow steps into this define.
It I uncomment these lines everything compiles without error and works fine.

Sorry for not having a better error description

**Comment by khoih-prog** [comment]
Hi @generationmake 

Thanks for your enhancement request, the new [**SAMD_TimerInterrupt** release v1.3.1](https://github.com/khoih-prog/SAMD_TimerInterrupt/releases/tag/v1.3.1) has just been published, with your Contribution noted in [**Contributions and Thanks**](https://github.com/khoih-prog/SAMD_TimerInterrupt#contributions-and-thanks).

Looking forward to receiving more Contributions from you.

Thanks and Regards,

---

### Releases v1.3.1

1. Fix compile error to some SAMD21-based boards, such as ADAFRUIT_FEATHER_M0, ARDUINO_SAMD_FEATHER_M0, ADAFRUIT_METRO_M0_EXPRESS, ARDUINO_SAMD_HALLOWING_M0 and ADAFRUIT_BLM_BADGE. Check [**Doesn't compile with Adafruit Feather M0** #2](https://github.com/khoih-prog/SAMD_TimerInterrupt/issues/2).
