### ISSUE TITLE
why only TC3 on SAMD51?

### ISSUE THREAD

**Issue by dwmj1950** [khoih-prog/SAMD_TimerInterrupt#29]
Hi,
I am just wondering why in your SAMD_TimerInterrupt project you only use TC3 for the SAMD51.
The Microchip data sheet for ATSAMD51J19A shows that there are 6 TC's and 2 TCC's.
In the code, only one (TC3) is used...Yet the others should be available to use also, right?

For the SAMD21 you use all available.

Am I missing something?

Thanks,
Don

**Comment by khoih-prog** [comment]
> The Microchip data sheet for ATSAMD51J19A shows that there are 6 TC's and 2 TCC's.
> In the code, only one (TC3) is used.

https://github.com/khoih-prog/SAMD_TimerInterrupt/blob/88c4a730ce3396cdf71f69936d24e6eb0d7f9b0a/examples/Argument_None/Argument_None.ino#L49

That's true, just TC3 is used for SAMD51. And I have no time, interest and intention to add other Timers to SAMD51. At least for now.

Sorry,

**Comment by dwmj1950** [comment]
No worries,

Thank you from replying so quickly.
I just wanted to know if there was a technical reason you did only TC3.
But it does not appear so.

It should be fairly easy for me to edit the existing code to include the other timers.

Thanks again,

Don

**Comment by khoih-prog** [comment]
Hi @dwmj1950 

> It should be fairly easy for me to edit the existing code to include the other timers.

When done, can you make the PR to improve the library and benefit many other users.
