### ISSUE TITLE
Problem with README.md

### ISSUE THREAD

**Issue by netskink** [khoih-prog/SAMD_TimerInterrupt#5]
The github readme has some examples.  The second one which demonstrates how to use a timer array needs the following adjustments.

In the setup routine, this call `ITimer.attachInterruptInterval` needs to be changed to `ITimer0.attachInterruptInterval`

Also in the setup routine, add `uint32_t lastMillis = 0; `

I realize you are putting a snippet of code, so the last revision could be omitted.  However, the iTimer vs iTimer0 change seems relevant even for a snippet.

**Comment by khoih-prog** [comment]
Hi John,

I'm closing this issue and we'll follow up via your PR [**fix for readme** #6](https://github.com/khoih-prog/SAMD_TimerInterrupt/pull/6)
